"""Build LaTeX comparison tables for white-paper sections."""

from __future__ import annotations

import argparse
import logging
import re
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)
REPO_ROOT = Path(__file__).resolve().parents[3]


def _parse_tab_main_att(path: Path) -> dict[str, float | None]:
    """Parse auto-generated tab_main_att.tex into estimator -> att."""
    out: dict[str, float | None] = {
        "full_panel": None,
        "matched": None,
        "residualized": None,
    }
    if not path.exists():
        return out
    text = path.read_text(encoding="utf-8")
    patterns = {
        "full_panel": r"full panel\) & ([\d\.\-]+)",
        "matched": r"matched sample\) & ([\d\.\-]+)",
        "residualized": r"tract trends \(matched sample\) & ([\d\.\-]+)",
    }
    for key, pat in patterns.items():
        m = re.search(pat, text)
        if m:
            try:
                out[key] = float(m.group(1))
            except ValueError:
                out[key] = None
    return out


def _fmt(x: float | None) -> str:
    if x is None or x != x:
        return "---"
    return f"{x:,.1f}".replace(",", "{,}")


def build_main_comparison_table(
    two_feat_dir: Path, five_feat_dir: Path, out_path: Path
) -> None:
    """Write 2-feature vs 5-feature matched ATT comparison table."""
    att2 = _parse_tab_main_att(two_feat_dir / "tables" / "tab_main_att.tex")
    att5 = _parse_tab_main_att(five_feat_dir / "tables" / "tab_main_att.tex")
    lines = [
        "% Auto-generated by build_matching_comparison_tables.py",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Specification & 2-feature matching & 5-feature matching \\\\",
        "\\midrule",
        (
            "Full-panel CS ATT (\\$/mo.) "
            f"& {_fmt(att2.get('full_panel'))} & {_fmt(att5.get('full_panel'))} \\\\"
        ),
        (
            "Matched CS ATT (\\$/mo.) "
            f"& {_fmt(att2.get('matched'))} & {_fmt(att5.get('matched'))} \\\\"
        ),
        (
            "Residualized CS ATT (precond. scale) "
            f"& {_fmt(att2.get('residualized'))} & {_fmt(att5.get('residualized'))} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", out_path)


def build_treatment_comparison_table(
    threshold_dir: Path, binary_dir: Path, out_path: Path
) -> None:
    """Write threshold vs binary treatment definition ATT comparison table."""
    att_th = _parse_tab_main_att(threshold_dir / "tables" / "tab_main_att.tex")
    att_bi = _parse_tab_main_att(binary_dir / "tables" / "tab_main_att.tex")
    lines = [
        "% Auto-generated by build_matching_comparison_tables.py",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Estimator & Intensity threshold & Binary \\\\",
        "\\midrule",
        (
            "Full-panel CS ATT "
            f"& {_fmt(att_th.get('full_panel'))} & {_fmt(att_bi.get('full_panel'))} \\\\"
        ),
        (
            "Matched CS ATT "
            f"& {_fmt(att_th.get('matched'))} & {_fmt(att_bi.get('matched'))} \\\\"
        ),
        (
            "Residualized CS ATT "
            f"& {_fmt(att_th.get('residualized'))} & {_fmt(att_bi.get('residualized'))} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", out_path)


def build_heterogeneity_table(csv_path: Path, out_path: Path) -> None:
    """Write heterogeneity summary table from analyzer CSV."""
    if not csv_path.exists():
        logger.warning("Missing heterogeneity CSV: %s", csv_path)
        return
    summary = pd.read_csv(csv_path)
    label_map = {
        "income": "Median income",
        "renter_share": "Renter share",
        "airbnb_density": "Airbnb density",
        "dose": "Prohibition dose",
        "cohort_timing": "Cohort timing",
    }
    lines = [
        "% Auto-generated by build_matching_comparison_tables.py",
        "\\begin{tabular}{llrr}",
        "\\toprule",
        "Moderator & Subgroup & ATT (\\$/mo.) & SE \\\\",
        "\\midrule",
    ]
    for _, row in summary.iterrows():
        split = label_map.get(str(row["split"]), str(row["split"]))
        subgroup = str(row["subgroup"]).title()
        att = _fmt(float(row["att"]))
        se = _fmt(float(row["se"]))
        lines.append(f"{split} & {subgroup} & {att} & ({se}) \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", out_path)


def build_spillover_table(csv_path: Path, out_path: Path) -> None:
    """Write spillover ATT summary table from analyzer CSV."""
    if not csv_path.exists():
        logger.warning("Missing spillover CSV: %s", csv_path)
        return
    row = pd.read_csv(csv_path).iloc[0]
    lines = [
        "% Auto-generated by build_matching_comparison_tables.py",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Quantity & Value \\\\",
        "\\midrule",
        f"Pooled spillover ATT (\\$/mo.) & {_fmt(float(row['att']))} \\\\",
        f"Standard error & ({_fmt(float(row['se']))}) \\\\",
        f"Spillover-treated tracts & {int(row['n_spillover'])} \\\\",
        f"Pure control tracts & {int(row['n_pure_control'])} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", out_path)


def build_robustness_comparison_table(
    k_csv_2: Path, k_csv_5: Path, out_path: Path
) -> None:
    """Write 2-feature vs 5-feature robustness sweep comparison at k=3."""
    if not k_csv_2.exists() or not k_csv_5.exists():
        logger.warning("Missing sweep CSVs; skipping robustness comparison table")
        return
    df2 = pd.read_csv(k_csv_2)
    df5 = pd.read_csv(k_csv_5)
    row2 = df2[df2["value"].astype(str) == "3"].iloc[0]
    row5 = df5[df5["value"].astype(str) == "3"].iloc[0]
    lines = [
        "% Auto-generated by build_matching_comparison_tables.py",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Estimator ($k=3$, $p=0.25$) & 2-feature & 5-feature \\\\",
        "\\midrule",
        (
            "Matched CS ATT "
            f"& {_fmt(float(row2['cs_matched_att']))} & {_fmt(float(row5['cs_matched_att']))} \\\\"
        ),
        (
            "Residualized CS ATT "
            f"& {_fmt(float(row2['cs_with_controls_att']))} & {_fmt(float(row5['cs_with_controls_att']))} \\\\"
        ),
        "\\bottomrule",
        "\\end{tabular}",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s", out_path)


def main() -> None:
    """CLI entrypoint for white-paper LaTeX comparison tables."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--two-feat-dir",
        default=str(REPO_ROOT / "output" / "did-cs-whitepaper-2feat-threshold"),
    )
    parser.add_argument(
        "--two-feat-binary-dir",
        default=str(REPO_ROOT / "output" / "did-cs-whitepaper-2feat-binary"),
    )
    parser.add_argument(
        "--five-feat-dir",
        default=str(REPO_ROOT / "output" / "did-cs-whitepaper-threshold"),
    )
    parser.add_argument(
        "--heterogeneity-dir",
        default=str(REPO_ROOT / "output" / "did-cs-heterogeneity-2feat"),
    )
    parser.add_argument(
        "--spillover-dir",
        default=str(REPO_ROOT / "output" / "did-cs-spillover-2feat"),
    )
    parser.add_argument(
        "--out-dir",
        default=str(REPO_ROOT / "docs" / "white-paper" / "tables"),
    )
    args = parser.parse_args()
    out_dir = Path(args.out_dir)

    build_main_comparison_table(
        Path(args.two_feat_dir),
        Path(args.five_feat_dir),
        out_dir / "tab_matching_att_comparison.tex",
    )
    build_treatment_comparison_table(
        Path(args.two_feat_dir),
        Path(args.two_feat_binary_dir),
        out_dir / "tab_treatment_comparison.tex",
    )
    build_heterogeneity_table(
        Path(args.heterogeneity_dir) / "cs_heterogeneity_summary.csv",
        Path(args.heterogeneity_dir) / "tables" / "tab_heterogeneity_summary.tex",
    )
    build_spillover_table(
        Path(args.spillover_dir) / "cs_spillover_summary.csv",
        Path(args.spillover_dir) / "tables" / "tab_spillover_summary.tex",
    )
    build_robustness_comparison_table(
        REPO_ROOT / "docs" / "robustness" / "k_neighbors_sweep_summary_2feat.csv",
        REPO_ROOT / "docs" / "robustness" / "k_neighbors_sweep_summary_5feat.csv",
        out_dir / "tab_matching_robustness_comparison.tex",
    )


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    main()
