"""Emit small LaTeX fragments (booktabs-style) for slides or appendix."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import pandas as pd

from housing.components.analyzers.cohort_att_latex import build_cohort_att_table_lines
from pipeline.base import Analyzer

logger = logging.getLogger(__name__)

MIN_YM_LEN = 7


def _num(x: object) -> float:
    try:
        v = float(x)
    except (TypeError, ValueError):
        return float("nan")
    return v


def _cell_att_se(att: float, se: float) -> str:
    if att != att:
        return "--- & ---"
    a = f"{att:,.1f}".replace(",", "{,}")
    if se != se:
        return f"{a} & ---"
    s = f"{se:,.2f}".replace(",", "{,}")
    return f"{a} & ({s})"


class LaTeXTableExporter(Analyzer):
    """Write ``tables/tab_*.tex`` under the DiD output directory."""

    def __init__(self, output_dir: str | Path) -> None:
        """Configure the DiD output directory for LaTeX table fragments."""
        super().__init__(
            "latex_whitepaper_tables",
            "Emit booktabs-ready LaTeX fragments for slides / paper appendix",
        )
        self.output_dir = Path(output_dir)

    def execute(self, context: dict[str, Any]) -> dict[str, Any]:
        """Write ``tables/tab_*.tex`` fragments from pipeline CSV/context artifacts."""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        tdir = self.output_dir / "tables"
        tdir.mkdir(parents=True, exist_ok=True)
        written: list[str] = []

        # --- Pooled ATTs (context) ---
        cs_full = context.get("cs_overall_att_full_panel") or {}
        cs = context.get("cs_overall_att") or {}
        csw = context.get("cs_overall_att_with_controls") or {}
        tab_main = [
            "% Auto-generated by LaTeXTableExporter — do not edit by hand.",
            "\\begin{tabular}{lrr}",
            "\\toprule",
            "Estimator & ATT (\\$/mo.) & SE \\\\",
            "\\midrule",
        ]
        if cs_full:
            tab_main.append(
                "Callaway--Sant'Anna (full panel) "
                + f"& {_cell_att_se(_num(cs_full.get('att')), _num(cs_full.get('se')))} \\\\"
            )
        tab_main.extend(
            [
                "Callaway--Sant'Anna (matched sample) "
                + f"& {_cell_att_se(_num(cs.get('att')), _num(cs.get('se')))} \\\\",
                "Callaway--Sant'Anna w/ ACS + tract trends (matched sample) "
                + f"& {_cell_att_se(_num(csw.get('att')), _num(csw.get('se')))} \\\\",
                "\\bottomrule",
                "\\end{tabular}",
            ]
        )
        p_main = tdir / "tab_main_att.tex"
        p_main.write_text("\n".join(tab_main) + "\n", encoding="utf-8")
        written.append(str(p_main))

        # --- honest pretrends ---
        hp_path = self.output_dir / "honest_pretrends_summary.csv"
        if hp_path.exists():
            hdf = pd.read_csv(hp_path)
            if not hdf.empty:
                row = hdf.iloc[0].to_dict()
                viol = row.get("violates_sign_restriction_all_nonpositive_pre")
                viol_yes = bool(viol) if pd.notna(viol) else False
                tab_hp = [
                    "% Auto-generated",
                    "\\begin{tabular}{lr}",
                    "\\toprule",
                    "Diagnostic & Value \\\\",
                    "\\midrule",
                    (
                        r"Max $\lvert$TWFE coef.$\rvert$ in pre-periods & "
                        f"{_num(row.get('max_abs_twfe_coef_pre')):.3f} \\\\"
                    ),
                    (
                        r"Max $\lvert$second difference$\rvert$ of pre-coefs & "
                        f"{_num(row.get('smoothness_second_diff_abs_max')):.3f} \\\\"
                    ),
                    "Any strictly positive pre-coef.? & "
                    + ("Yes" if viol_yes else "No")
                    + " \\\\",
                    "\\bottomrule",
                    "\\end{tabular}",
                ]
                p_hp = tdir / "tab_honest_pretrends.tex"
                p_hp.write_text("\n".join(tab_hp) + "\n", encoding="utf-8")
                written.append(str(p_hp))

        sutva_donut = self.output_dir / "sutva_donut_summary.csv"
        if sutva_donut.exists():
            ddf = pd.read_csv(sutva_donut)
            label_map = {
                "full_sample": "Full matched control pool",
                "never_adjacent_treated_neighbour": "Adjacent never-treated controls",
                "never_isolated_neighbours": "Isolated never-treated controls",
            }
            lines = [
                "% Auto-generated",
                "\\begin{tabular}{lrr}",
                "\\toprule",
                "Subsampling contrast & $\\widehat{\\mathrm{ATT}}$ & SE \\\\",
                "\\midrule",
            ]
            for _, rr in ddf.iterrows():
                raw = str(rr.get("subgroup", ""))
                lbl = label_map.get(raw, raw.replace("_", " "))
                lines.append(
                    lbl
                    + f" & {_cell_att_se(_num(rr.get('att')), _num(rr.get('se')))} \\\\"
                )
            lines.extend(["\\bottomrule", "\\end{tabular}"])
            p_sd = tdir / "tab_sutva_donut.tex"
            p_sd.write_text("\n".join(lines) + "\n", encoding="utf-8")
            written.append(str(p_sd))

        sutva_dose = self.output_dir / "sutva_dose_quartiles.csv"
        if sutva_dose.exists():
            dof = pd.read_csv(sutva_dose)
            lines = [
                "% Auto-generated",
                "\\begin{tabular}{lccc}",
                "\\toprule",
                (
                    "Neighbour-treated share quartile & "
                    "$n$ (never-tr.) & Mean share & "
                    "$\\widehat{\\mathrm{ATT}}$ (SE) \\\\"
                ),
                "\\midrule",
            ]
            for _, rr in dof.iterrows():
                lab = str(rr.get("label") or rr.get("quartile", "")).replace("_", "\\_")
                nnt = rr.get("n_never_tr", "")
                msh = _num(rr.get("mean_neighbour_share_treated_mid"))
                ms = "---" if msh != msh else f"{msh:.2f}"
                att = _num(rr.get("att"))
                se = _num(rr.get("se"))
                att_se = "---" if att != att else f"{att:,.1f}".replace(",", "{,}")
                se_c = ""
                if att == att and se == se:
                    se_c = f" ({se:,.2f})".replace(",", "{,}")
                elif att == att:
                    se_c = ""
                lines.append(f"{lab} & {nnt} & {ms} & {att_se}{se_c} \\\\")
            lines.extend(["\\bottomrule", "\\end{tabular}"])
            p_do = tdir / "tab_sutva_dose.tex"
            p_do.write_text("\n".join(lines) + "\n", encoding="utf-8")
            written.append(str(p_do))

        # --- Data funnel + cohort descriptives (policy decks) ---
        panel_raw_path = self.output_dir / "did_panel_data.csv"
        panel_ov_path = self.output_dir / "did_descriptive_panel_overview.csv"
        cohort_stats_path = self.output_dir / "did_descriptive_cohort_stats.csv"
        sample_lineage_path = self.output_dir / "did_descriptive_sample_lineage.csv"

        def _currency0(x: float) -> str:
            if x != x:
                return "---"
            inner = f"{x:,.0f}".replace(",", "{,}")
            return f"${inner}$"

        if sample_lineage_path.exists():
            ldf = pd.read_csv(sample_lineage_path)
            if not ldf.empty:

                def _fmt_int(value: object) -> str:
                    if pd.isna(value):
                        return "---"
                    return str(int(value))

                funnel_lines = [
                    "% Auto-generated",
                    "\\begin{tabular}{@{} l l r r r @{}}",
                    "\\toprule",
                    "Stage & Sample slice & Tracts & Treated & Never-treated \\\\",
                    "\\midrule",
                ]
                for _, rw in ldf.iterrows():
                    label = str(rw.get("stage_code", ""))
                    name = str(rw.get("stage_label", ""))
                    tracts = _fmt_int(rw.get("n_tracts"))
                    treated = _fmt_int(rw.get("treated_tracts"))
                    never = _fmt_int(rw.get("never_treated_tracts"))
                    funnel_lines.append(
                        f"\\textbf{{{label}}} & {name} & {tracts} & {treated} & {never} \\\\"
                    )
                funnel_lines.extend(["\\bottomrule", "\\end{tabular}"])
                p_funnel = tdir / "tab_data_funnel.tex"
                p_funnel.write_text("\n".join(funnel_lines) + "\n", encoding="utf-8")
                written.append(str(p_funnel))

        elif panel_raw_path.exists() and panel_ov_path.exists():
            pdf_raw = pd.read_csv(
                panel_raw_path,
                usecols=["tract_geoid", "treated"],
                low_memory=False,
            )
            tg_mx = pdf_raw.groupby("tract_geoid")["treated"].max()
            n_raw = int(tg_mx.index.nunique())
            n_raw_tr = int((tg_mx >= 1).sum())
            n_raw_nt = n_raw - n_raw_tr

            overview = pd.read_csv(panel_ov_path).iloc[0].to_dict()
            n_ma = int(overview.get("n_tracts", 0))
            n_ma_tr = int(overview.get("tracts_eventually_treated", 0))
            n_ma_nt = int(overview.get("tracts_never_treated", 0))

            n_cs_cohorts = 0
            sum_cs_tracts = 0
            if cohort_stats_path.exists():
                cstat_df = pd.read_csv(cohort_stats_path)
                if not cstat_df.empty:
                    n_cs_cohorts = len(cstat_df)
                    sum_cs_tracts = int(cstat_df["n_tracts"].sum())

            remnant_note = ""
            if sum_cs_tracts > 0 and sum_cs_tracts < n_ma_tr:
                remnant_note = (
                    f" (Excludes {int(n_ma_tr - sum_cs_tracts)} treated tract(s)"
                    r" whose adoption-month cohort has $<5$ units in pooled CS)."
                )

            funnel_lines = [
                "% Auto-generated",
                "\\begin{tabular}{@{} l p{7cm} r r r @{}}",
                "\\toprule",
                (
                    r"Stage & Description & Total tracts & Treated "
                    r"& Never-treated \\"
                ),
                "\\midrule",
                (
                    r"\textbf{A} & Raw Chicago tract$\times$month panel "
                    r"(ZIP rent crosswalk; prohibited-building timing)."
                    r" Before pre-treatment matching."
                    f"& {n_raw} & {n_raw_tr} & {n_raw_nt} \\\\"
                ),
                (
                    r"\textbf{B} & Matched DiD panel: retain never-treated tract if "
                    r"standardized pre-treatment slope and average rent are among the nearest "
                    r"$k{=}3$ to at least one treated tract "
                    r"($\geq 6$ pre-months)."
                    f"& {n_ma} & {n_ma_tr} & {n_ma_nt} \\\\"
                ),
                (
                    r"\textbf{C} & CS-visible adoption months ($\geq 5$ treated)."
                    f" {n_cs_cohorts} cohort months; "
                    f"{sum_cs_tracts} treated tracts in tables/figures.{remnant_note} \\\\"
                ),
                "\\bottomrule",
                "\\end{tabular}",
            ]
            p_funnel = tdir / "tab_data_funnel.tex"
            p_funnel.write_text("\n".join(funnel_lines) + "\n", encoding="utf-8")
            written.append(str(p_funnel))

        if cohort_stats_path.exists():
            cstat_rd = pd.read_csv(cohort_stats_path)
            if not cstat_rd.empty:
                c_lines = [
                    "% Auto-generated",
                    "\\begin{tabular}{@{} l r r r r r r @{}}",
                    "\\toprule",
                    "Cohort & $n$ & Share "
                    "& Rent "
                    "& Inc. "
                    "& Bach.\\% "
                    "& Rented\\% \\\\",
                    "\\midrule",
                ]
                for _, rw in cstat_rd.iterrows():
                    m_raw = str(rw.get("first_prohibition_month", ""))
                    ym = m_raw[:MIN_YM_LEN] if len(m_raw) >= MIN_YM_LEN else m_raw
                    nt_val = rw.get("n_tracts", "")
                    nt_s = str(int(nt_val)) if pd.notna(nt_val) else ""
                    shr = rw.get("share_of_treated_tracts")
                    shr_s = f"{float(shr):.2f}" if pd.notna(shr) else "---"
                    br_val = rw.get("mean_baseline_rent")
                    inc_val = rw.get("mean_median_income")
                    br_s = _currency0(float(br_val)) if pd.notna(br_val) else "---"
                    inc_s = _currency0(float(inc_val)) if pd.notna(inc_val) else "---"
                    pb = rw.get("mean_pct_bachelor")
                    pr = rw.get("mean_pct_rented")
                    pb_s = f"{float(pb):.1f}" if pd.notna(pb) else "---"
                    pr_s = f"{float(pr):.1f}" if pd.notna(pr) else "---"
                    c_lines.append(
                        f"{ym} & {nt_s} & {shr_s} & {br_s} & "
                        f"{inc_s} & {pb_s} & {pr_s} \\\\"
                    )
                c_lines.extend(["\\bottomrule", "\\end{tabular}"])
                p_coh = tdir / "tab_cohort_descriptive.tex"
                p_coh.write_text("\n".join(c_lines) + "\n", encoding="utf-8")
                written.append(str(p_coh))

        att_summary_path = self.output_dir / "did_cs_att_summary.csv"
        pretrend_sig_path = self.output_dir / "did_cs_pretrend_significance.csv"
        if att_summary_path.exists():
            att_df = pd.read_csv(att_summary_path)
            pretrend_df = (
                pd.read_csv(pretrend_sig_path) if pretrend_sig_path.exists() else None
            )
            cohort_lines = build_cohort_att_table_lines(att_df, pretrend_df)
            if cohort_lines:
                p_catt = tdir / "tab_cohort_att.tex"
                p_catt.write_text("\n".join(cohort_lines) + "\n", encoding="utf-8")
                written.append(str(p_catt))

        logger.info("LaTeX tables: %s", written)
        return {"latex_whitepaper_tables": written}
